### ISSUE TITLE
Pic shown sideways

### ISSUE THREAD

**Issue by denis-ev** [mykle1/MMM-EasyPix#1]
Hey,

your EasyPix module is great, but I have one pic that is always shown sideways and I can't rotate it.
Have you had the problem before?

Best regards,
Denis

**Comment by mykle1** [comment]
No sir, I have not, nor has anyone else that I know of. If it is just one picture then you can assume it's the picture that is causing the issue

**Comment by ghost** [comment]
Yeah it's probably the picture.
