### ISSUE TITLE
info regarding update interval

### ISSUE THREAD

**Issue by mistrysiddh** [mykle1/MMM-EasyPix#10]
hey can you explain to me the update time interval which you have set in the module

```
updateInterval: 30 * 60 * 1000,
```

**Comment by KristjanESPERANTO** [comment]
The module is reloaded at this interval. The value is in milliseconds - 30 * 60 * 1000 is 30 minutes. As far as I understand it so far, there should be no reason to change this value.

**Comment by mistrysiddh** [comment]
ok thanks
