### ISSUE TITLE
pic not showing plus addition of multiple pics

### ISSUE THREAD

**Issue by justjim1220** [mykle1/MMM-EasyPix#2]
any chance you can give an example of the entry to add multiple pics. I've tried several different methods and just can't get it to show any pics. On top of it all, can't get it to show any pics now, Help!

**Comment by mykle1** [comment]
Hi, I'm sorry you're having some difficulty with this module. I'm sure it is something simple. If you would kindly create a "Troubleshooting" topic on the MagicMirror forums I will be more than happy to assist you

**Comment by snowman3** [comment]
Hey @mykle1 I am using this module to display a .png file on my magic mirror. I'm updating this .png file every 15 minutes in the background using a crontab tho it is not updating on the magic mirror screen. Do you know a way to make this update every so often? Thanks in advance.
