### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-EasyPix#4]
Hi,
I like your module! I use it to show a single pic, but that is refreshed every 5min. But it never refresh on my mirror, unless I restart it.

Therefore, Is it possible to set a refresh rate? Something you can implement? :D

**Comment by mykle1** [comment]
Feel free to fork the repo and make the changes. I'd be glad to merge your changes. I wrote this module to be used with Hello-Lucy. I did not want the image refreshing while in use with Hello-Lucy. Doesn't seem to be a reason to refresh with only one image being displayed. Also, there are other image modules that you could use if this is not working for you

**Comment by mykle1** [comment]
> Hi,
> I like your module! I use it to show a single pic, but that is refreshed every 5min. But it never refresh on my mirror, unless I restart it.
> 
> Therefore, Is it possible to set a refresh rate? Something you can implement? :D

I know this was a long time in coming but I just got around to fixing the refresh issue you posted. The module will now refresh every 30 minutes by default or you can change it in the config
