### ISSUE TITLE
No Sound.

### ISSUE THREAD

**Issue by nosee818** [mykle1/MMM-EasyPix#5]
I can run this module show the picture but not play sound. This device can be played directly by clicking on the MP3 file in the system.

I didn't change any code.

               {
                        //disabled : true,
                        module: "MMM-EasyPix",
                        position: "top_center",
                        config: {
                                picName: "face.gif", // Enter the picture file name.
                                maxWidth: "75%",        // Size picture precisely. Retains aspect ratio.
                                sounds: ["1.mp3", "me2.mp3"],  // mp3 sound file names in quotes seperated by commas for Hello-Lucy
                                updateInterval: 30 * 60 * 1000,     // updates display
                                        animationSpeed: 3000,
                        }
                },

**Comment by mykle1** [comment]
You would only hear the sound files if you are running Hello-Lucy AND MMMEasyPix. It is the Hello-Lucy voice commands that trigger the sound files. Also, when Hello-Lucy loads it sends a notification to EasyPix to play those sound files at start up
