### ISSUE TITLE
too small gif

### ISSUE THREAD

**Issue by santiagos5** [mykle1/MMM-EasyPix#6]
hello, 

my config is :
`{
			    module: "MMM-EasyPix",
                            position: "top_left",
				config: {
					picName: "AI.gif", // Enter the picture file name.
					maxWidth: "100%",        // Size picture precisely. Retains aspect ratio.
					updateInterval: 30 * 60 * 1000,     // updates display
					animationSpeed: 3000,
				}
			},`

but my gif (blu circle) is too small.. Why? resolution image is 400x400
[https://www.dropbox.com/s/rr91l8hq1qdusvy/Cattura.PNG?dl=0](url)

**Comment by mykle1** [comment]
That link doesn't take me to a picture. You probably have some css rule that is affecting the gif. Please continue this in the forum
