### ISSUE TITLE
Multiple Pictures

### ISSUE THREAD

**Issue by Raven4150** [mykle1/MMM-EasyPix#7]
Hi, 
I would need your help. I have uploaded a couple of pictures but they don't show up when I copy the entry. Is there something I do wrong. I tried it a couple of different ways. 
picName: "527.jpg","18.jpg" or
picName: ["527.jpg","18.jpg"],
both doesn't work. Please I need your help.
Cheers

**Comment by TokingGnome** [comment]
did you ever figure out a fix for this? I am also trying to use this module in a new mirror build and cannot get multiple photos to work at all

**Comment by Raven4150** [comment]
No still working on it. No idea what I am doing wrong

**Comment by ghost** [comment]
Did you find a solution yet?

**Comment by mykle1** [comment]
As it is, you can't have more than one picture at a time but I'm pretty sure you can have multiple config entries for EasyPix with a different picture in each one. Give it a shot. Any further issues please post a topic on the forum
