### ISSUE TITLE
Previous Issues On Forums Not Answered

### ISSUE THREAD

**Issue by ghost** [mykle1/MMM-EasyPix#8]
Hello @mykle1,
I've been having some of the same issues other people are having.  Could you please reach out to us in the forums? 
[https://forum.magicmirror.builders/search?term=mmm-easypix&in=titlesposts](url)
#7 
Your module is amazing,
Ethyx

**Comment by mykle1** [comment]
Well, you could tell me what the issue is first. Instead of me trying to find you on the forum you should create a topic in Troubleshooting with "MMM-EasyPix" in the title and I'll answer your questions there. Sound good?
